### ISSUE TITLE
Move the halloween icon to images

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#349]
Also change the corresponding links

**Comment by adamxtokyo** [comment]
I call dibs on this issue 😄 Will fix it right away!

**Comment by adamxtokyo** [comment]
Just wanted to give some feedback after clearing the issue;

Because the instructions are inconsistent (readme says images go in ./img/, while file structure implies they should go in ./src/images/), different contributors are doing different things. This has lead to a messy code base and might be worth looking into.

Other than that, I want to say thanks to @sudz123 👏🙏😌
It's fun to get started with OSS contribution and I'm happy these kinds of repos exist!

**Comment by adamxtokyo** [comment]
Ok, so it seems like @vidban pushed a commit fixing the issue and @diptanshu-sopho merged it while my commit was still in code review. Not cool guys... I posted here saying I'd take care of it and I spent a fair amount of my own time doing so ☹️

**Comment by sudz123** [comment]
@adamxtokyo Apologies for this, please refer to my comments in #352 . This is bound to keep happening if you work on easy issues. I would suggest add your own personal page and add features to it. That way it would make both our lives easier.
